### ISSUE TITLE
App shows CGContextDrawPath error while doing mosaic on picture

### ISSUE THREAD

**Issue by XiandWang** [a130785/WWImageEdit#1]
Thank you for the demo!

While I was doing mosaic effect on an image, I saw this:

Error: CGContextDrawPath: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

However, the app did not crash.

**Comment by a130785** [comment]
Thank you for reminding.I know the error is because, the _UIGraphicsGetCurrentContext()_ is nil, and because of that, I get this error, Only in _drawRect:_ method,_UIGraphicsGetCurrentContext()_ is valid,and We needs to use _UIGraphicsBeginImageContextWithOptions(rect.size,YES,0)_;
Finally, I also solve the other error
